name = "PolynomialGTM"
uuid = "d0486fca-abc3-4e94-983c-1d27790b80a4"
authors = ["Joe Carpinelli <jdcarpinelli@gmail.com>"]
version = "1.4.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DocStringExtensions = "0.8, 0.9"
Memoize = "0.4"
ModelingToolkit = "~9.3, 9"
Symbolics = "5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
